### PR TITLE
feat: support redux-devtools

### PR DESCRIPTION
**Pull request by SebastianM**
Adds support for the redux-devtools.

This fixes also the type for the `plugins` array in the options. It was not possible to provide a class name in the configuration.

Open issue: I'm not able to inject `Ngxs` into the Plugin (it's always `undefined`). So I'm not able to set the initial state.

### CODE REVIEW

**Comment by amcdnl** [comment]
WOAH! YOU ARE EPIC! I WAS LITERALLY JUST ABOUT TO START THIS!

**Comment by SebastianM** [comment]
Thanks man! 😄I really like the design! I'm sure this will be a popular project.

**Comment by amcdnl** [comment]
Maybe its undefined because its circular?

**Comment by SebastianM** [comment]
Hmm no don't think so. Got no error and I also tried to inject Injector - was also undefined without errors. Haven't had the time yet to do more research.

**Comment by amcdnl** [comment]
Maybe I need to export the services in my ngxs module?

**Comment by amcdnl** [comment]
Fixed it :)

**Comment by SebastianM** [comment]
Cool! Btw: I think that's the line that prevents DI in plugins: https://github.com/amcdnl/ngxs/blob/master/src/plugin-manager.ts#L12

**Pull request merged**
